server:
  port: 8081
  error:
    include-exception: false
    include-stacktrace: never # ?? ??? stacktrace ??? ??? ? ??

spring:
  profiles:
    group:
      "local": "local,common"
      "dev": "dev,common"
      "prod": "prod,common"
---
# ?? ?? ??
spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/h2DB/gu-pos
    #    url: https://1ab2-116-36-82-239.ngrok-free.app/h2BD/adruck-admin
    username: root
    password: ''
  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

    open-in-view: false # OSIV ??

  thymeleaf:
    cache: false
    prefix: file:///Users/gimgeon-u/neoclue/project/gupos-module/gupos-web-order/src/main/resources/templates/
    #    prefix: file:///Users/hojintop/IdeaProjects/dongne-module/dongne-admin/src/main/resources/templates/

  web:
    resources:
      static-locations:
        - classpath:/static/
#        - file:/Users/gimgeon-u/neoclue/dongne/upload

  mvc:
    static-path-pattern: /**


---
## ??
spring:
  config:
    activate:
      on-profile: "common"

  application:
    name: gupos-web-order

  data:
    web:
      pageable:
        one-indexed-parameters: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging.level:
  org.hibernate.SQL: trace # ??? ??
