server:
  port: 8080
  error:
    include-exception: false
    include-stacktrace: never # ?? ??? stacktrace ??? ??? ? ??

spring:
  profiles:
    group:
      "local": "local,common"
      "dev": "dev,common"
      "prod": "prod,common"
---
# ?? ?? ??
spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/h2DB/gu-pos
    #    url: https://1ab2-116-36-82-239.ngrok-free.app/h2BD/adruck-admin
    username: root
    password: ''
  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

    open-in-view: false # OSIV ??
    #      static-locations: file:///Users/hojintop/IdeaProjects/dongne/src/main/resources/static/

  web:
    resources:
      static-locations: file:/Users/gimgeon-u/intelliJProject/upload


---
## ??
spring:
  config:
    activate:
      on-profile: "common"

  application:
    name: gupos-api

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /files/**

  #  mvc:
  #    problemdetails:
  #      enabled: true

  data:
    web:
      pageable:
        one-indexed-parameters: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging.level:
  org.hibernate.SQL: trace # ??? ??